### ISSUE TITLE
Issue with reviving others while still in the same party (1.18.2)

### ISSUE THREAD

**Issue by AllieSniperian** [EtherealOnyx/PartiesMod#5]
Using Parties [1.18.2] - 0.4.0
with both (independently tested)
Hardcore Revival (8.0.1)
PlayerRevive (2.0.19)

Both of these caused Internal Server Issues witch crashed one of the clients, so long as both players were in the same party, with one attempting to revive another.

This issue was experienced in the KoboldPitaya mod pack, on the off chance another mod was causing the issue in addition. Versions 2.1.0 and 2.1.1

Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
        at io.sedu.mc.parties.data.PlayerData.setReviveProg(PlayerData.java:139) ~[sedparties-1.18.2-0.4.0.jar%23230!/:?] {re:mixin,re:classloading}
        at io.sedu.mc.parties.api.hardcorerevival.HREventHandler.lambda$onEntityTick$4(HREventHandler.java:50) ~[sedparties-1.18.2-0.4.0.jar%23230!/:?] {re:mixin,re:classloading}
        at io.sedu.mc.parties.api.hardcorerevival.HRHandler.getReviveProgress(HRHandler.java:28) ~[sedparties-1.18.2-0.4.0.jar%23230!/:?] {re:classloading}
        at io.sedu.mc.parties.api.hardcorerevival.HREventHandler.onEntityTick(HREventHandler.java:45) ~[sedparties-1.18.2-0.4.0.jar%23230!/:?] {re:mixin,re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_1464_HREventHandler_onEntityTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:879) ~[forge-1.18.2-40.2.0-universal.jar%23300!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}

**Comment by EtherealOnyx** [comment]
Thank you for the report. I thought I fixed all types of these errors...it will be fixed shortly.

**Comment by EtherealOnyx** [comment]
This should be fixed in version 0.4.1 which was just released [here.](https://www.curseforge.com/minecraft/mc-mods/parties/files/4499839)

The side effects of this error were quite grave in which the player would be forced to die on logout (based on config settings for the revival mods) and not even be able to log back in. I apologize for this and hope it didn't ruin your playthrough (too much).  Thanks again for the report!
